//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Host) DeepCopyInto(out *Host) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Host.
func (in *Host) DeepCopy() *Host {
	if in == nil {
		return nil
	}
	out := new(Host)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Host) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostList) DeepCopyInto(out *HostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Host, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostList.
func (in *HostList) DeepCopy() *HostList {
	if in == nil {
		return nil
	}
	out := new(HostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostObservation) DeepCopyInto(out *HostObservation) {
	*out = *in
	if in.Contacts != nil {
		in, out := &in.Contacts, &out.Contacts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ContactGroups != nil {
		in, out := &in.ContactGroups, &out.ContactGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Parents != nil {
		in, out := &in.Parents, &out.Parents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Hostgroups != nil {
		in, out := &in.Hostgroups, &out.Hostgroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ActiveChecksEnabled != nil {
		in, out := &in.ActiveChecksEnabled, &out.ActiveChecksEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PassiveChecksEnabled != nil {
		in, out := &in.PassiveChecksEnabled, &out.PassiveChecksEnabled
		*out = new(bool)
		**out = **in
	}
	if in.EventHandlerEnabled != nil {
		in, out := &in.EventHandlerEnabled, &out.EventHandlerEnabled
		*out = new(bool)
		**out = **in
	}
	if in.FlapDetectionEnabled != nil {
		in, out := &in.FlapDetectionEnabled, &out.FlapDetectionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.FlapDetectionOptions != nil {
		in, out := &in.FlapDetectionOptions, &out.FlapDetectionOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProcessPerfData != nil {
		in, out := &in.ProcessPerfData, &out.ProcessPerfData
		*out = new(bool)
		**out = **in
	}
	if in.RetainStatusInformation != nil {
		in, out := &in.RetainStatusInformation, &out.RetainStatusInformation
		*out = new(bool)
		**out = **in
	}
	if in.RetainNonstatusInformation != nil {
		in, out := &in.RetainNonstatusInformation, &out.RetainNonstatusInformation
		*out = new(bool)
		**out = **in
	}
	if in.CheckFreshness != nil {
		in, out := &in.CheckFreshness, &out.CheckFreshness
		*out = new(bool)
		**out = **in
	}
	if in.NotificationsEnabled != nil {
		in, out := &in.NotificationsEnabled, &out.NotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.FreeVariables != nil {
		in, out := &in.FreeVariables, &out.FreeVariables
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostObservation.
func (in *HostObservation) DeepCopy() *HostObservation {
	if in == nil {
		return nil
	}
	out := new(HostObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostParameters) DeepCopyInto(out *HostParameters) {
	*out = *in
	if in.Contacts != nil {
		in, out := &in.Contacts, &out.Contacts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ContactGroups != nil {
		in, out := &in.ContactGroups, &out.ContactGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Parents != nil {
		in, out := &in.Parents, &out.Parents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Hostgroups != nil {
		in, out := &in.Hostgroups, &out.Hostgroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ActiveChecksEnabled != nil {
		in, out := &in.ActiveChecksEnabled, &out.ActiveChecksEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PassiveChecksEnabled != nil {
		in, out := &in.PassiveChecksEnabled, &out.PassiveChecksEnabled
		*out = new(bool)
		**out = **in
	}
	if in.EventHandlerEnabled != nil {
		in, out := &in.EventHandlerEnabled, &out.EventHandlerEnabled
		*out = new(bool)
		**out = **in
	}
	if in.FlapDetectionEnabled != nil {
		in, out := &in.FlapDetectionEnabled, &out.FlapDetectionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.FlapDetectionOptions != nil {
		in, out := &in.FlapDetectionOptions, &out.FlapDetectionOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProcessPerfData != nil {
		in, out := &in.ProcessPerfData, &out.ProcessPerfData
		*out = new(bool)
		**out = **in
	}
	if in.RetainStatusInformation != nil {
		in, out := &in.RetainStatusInformation, &out.RetainStatusInformation
		*out = new(bool)
		**out = **in
	}
	if in.RetainNonstatusInformation != nil {
		in, out := &in.RetainNonstatusInformation, &out.RetainNonstatusInformation
		*out = new(bool)
		**out = **in
	}
	if in.CheckFreshness != nil {
		in, out := &in.CheckFreshness, &out.CheckFreshness
		*out = new(bool)
		**out = **in
	}
	if in.NotificationsEnabled != nil {
		in, out := &in.NotificationsEnabled, &out.NotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.FreeVariables != nil {
		in, out := &in.FreeVariables, &out.FreeVariables
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostParameters.
func (in *HostParameters) DeepCopy() *HostParameters {
	if in == nil {
		return nil
	}
	out := new(HostParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostSpec) DeepCopyInto(out *HostSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostSpec.
func (in *HostSpec) DeepCopy() *HostSpec {
	if in == nil {
		return nil
	}
	out := new(HostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostStatus) DeepCopyInto(out *HostStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostStatus.
func (in *HostStatus) DeepCopy() *HostStatus {
	if in == nil {
		return nil
	}
	out := new(HostStatus)
	in.DeepCopyInto(out)
	return out
}
